# Generated by Django 4.1.6 on 2023-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectorshop', '0003_rename_user_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='/media/images/products/nullproduct.jpg', upload_to='images/'),
        ),
    ]
