# Generated by Django 4.1.6 on 2023-02-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectorshop', '0008_category_tag_remove_article_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categories',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tag',
        ),
    ]
